### ISSUE TITLE
Sprint 0: Métricas del proyecto

### ISSUE THREAD

**Issue by zeditio** [PupiUTN/Agiles#60]
Horas reales de trabajo: 2:30 hs
Horas reales de review: 

Review request: @jorgecons @fbackhaus @LorenzattiGabriel @efradiaz 

Resultado: [https://docs.google.com/document/d/1WQpboi3vze9tj0A9X5pv1eG1ci4S0ao1yxrPzs5BBsY/edit#heading=h.duzcq5649zp](https://docs.google.com/document/d/1WQpboi3vze9tj0A9X5pv1eG1ci4S0ao1yxrPzs5BBsY/edit#heading=h.duzcq5649zp )

**Comment by jorgecons** [comment]
Revisada, está bastante bien. Corregí unas cosas del proceso, donde también estimamos el esfuerzo con poker planning y si da menos de 8, la tomamos. 
De las métricas, hay un par que no me cierran, como el desvio de horas. Igual sirven y si en un futuro decidimos sacarlas, las sacamos.
