### ISSUE TITLE
Sprint 0: Gestión de Configuración del Proyecto

### ISSUE THREAD

**Issue by zeditio** [PupiUTN/Agiles#61]
Hora trabajada : 1
el documento se encuentra en google drive

**Comment by zeditio** [comment]
@LorenzattiGabriel estaria bueno que expliquemos el modelo de branching que vamos a usar.
Ademas las buenas practicas dicen que la condigracion no debe estar hardcodeada si no en archivos de configuracion. Con esto cambias algo del proyecto sin hacer build.

**Comment by jorgecons** [comment]
@zeditio las branches no deberían estar hardcordeadas. Eso esta claro, pero se refiere a la estructura que van a tener los archivos de configuracion a implementar. Esto es solo la documentacion que dice que va ser, no cómo

**Comment by jorgecons** [comment]
@LorenzattiGabriel de todos modos, mucho copy&paste.... se supone que es redacción tuya, no rearmar de paginas

**Comment by LorenzattiGabriel** [comment]
me parece que si esta realizado porque tenes que poner a inventar vos un
branching model, no tiene sentido, si ya tenes el modelo lo implementas a
tu forma no lo inventas de 0 y lo escribis vos, yo busque el modelo y lo
arme yo, en el que me referencie tiene mas modelos de branch, para release
 para bug, etc y yo lo arme mas básico. el copy paste me lo paso por los ya
sabes donde, me traduci la página y la arme a mi forma pero saque toda la
info de ahi, no me voy a poner a inventar un branching model.

2017-06-14 21:45 GMT-03:00 Jorge Constable <notifications@github.com>:
