### ISSUE TITLE
Yo como Equipo quiero tener documentacion de testing en la misma herramienta para llevar un mejor control.

### ISSUE THREAD

**Issue by zeditio** [PupiUTN/Agiles#63]

**Comment by Lucassala** [comment]
Inicio de pruebas

**Comment by efradiaz** [comment]
Por qué esta cerrada esta?

**Comment by zeditio** [comment]
Era algo de ágiles. Aveces vamos a tener la misma historia repetida a lo largo de las Sprints. Pasa que es algo tan general que se cierra y se crea una nueva en vez de moverse.
